# Generated by Django 6.1 on 2026-08-12 21:30

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('symbol', models.CharField(max_length=16)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.utils.Utils.generic_image_path)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250)),
                ('title_en', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('symbol', models.CharField(max_length=16)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.utils.Utils.generic_image_path)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('today_price', models.DecimalField(decimal_places=8, max_digits=25)),
                ('fee_sell', models.DecimalField(decimal_places=8, default=0.0, help_text='درصد کارمزد فروش', max_digits=25)),
                ('fee_buy', models.DecimalField(decimal_places=8, default=0.0, help_text='درصد کارمزد خرید', max_digits=25)),
                ('fee_sell_fixed_value', models.DecimalField(decimal_places=8, default=0.0, help_text='مقدار ثابت کارمزد فروش', max_digits=25)),
                ('fee_buy_fixed_value', models.DecimalField(decimal_places=8, default=0.0, help_text='مقدار ثابت کارمزد خرید', max_digits=25)),
                ('fee_strategy', models.CharField(blank=True, choices=[('1', 'only_percent'), ('2', 'only_fixed_value'), ('3', 'buy_percent__sell_fixed'), ('4', 'buy_fixed__sell_percent'), ('5', 'percent_to_max_fixed')], max_length=32, null=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capital.assettype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price_sar_be_sar', models.DecimalField(decimal_places=8, max_digits=25)),
                ('price_buy', models.DecimalField(decimal_places=8, max_digits=25)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=25)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capital.asset')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_creator_%(model_name)s', to=settings.AUTH_USER_MODEL)),
                ('editor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_editor_%(model_name)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=8, help_text='قیمت تراکنش', max_digits=25)),
                ('fee', models.DecimalField(decimal_places=8, help_text='کارمزد تراکنس', max_digits=25)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='تعداد دارایی معامله شده', max_digits=25)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_creator_%(model_name)s', to=settings.AUTH_USER_MODEL)),
                ('editor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_editor_%(model_name)s', to=settings.AUTH_USER_MODEL)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capital.transactiontype')),
                ('user_asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capital.userasset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
