# Generated by Django 6.1 on 2026-08-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userasset',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
