# Generated by Django 6.1 on 2026-08-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0002_userasset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='max_decimal_point',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
