# Generated by Django 6.1 on 2026-08-12 12:35

import aaa.managers
import aaa.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable public identifier safe to expose in APIs.', unique=True, verbose_name='public id')),
                ('email', models.EmailField(blank=True, help_text='Unique email address. Optional if a phone number is set.', max_length=254, null=True, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, help_text='Unique phone number in international format. Optional if an email is set.', max_length=20, null=True, unique=True, validators=[aaa.validators.validate_phone], verbose_name='phone number')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_email_verified', models.BooleanField(default=False, help_text='Designates whether the email address has been verified.', verbose_name='email verified')),
                ('is_phone_verified', models.BooleanField(default=False, help_text='Designates whether the phone number has been verified.', verbose_name='phone verified')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the account has completed verification (at least one identifier confirmed).', verbose_name='verified')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', aaa.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40, verbose_name='provider')),
                ('provider_user_id', models.CharField(max_length=255, verbose_name='provider user id')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('date_connected', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date connected')),
                ('user', models.ForeignKey(help_text='The local user this external identity belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'social account',
                'verbose_name_plural': 'social accounts',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='aaa_user_email_fda76b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='aaa_user_phone_n_5d851d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'provider_user_id')},
        ),
    ]
